export const MAX_LENGTH_UNCHANGED_URL = 20;
export const MAX_LENGTH_UNCHANGED_URL_SMALL = 11;

export const FIRST_FOOTER_LINK_OF_CHILDREN = 0;
export const SECOND_FOOTER_LINK_OF_CHILDREN = 1;
export const THIRD_FOOTER_LINK_OF_CHILDREN = 2;
